--- # Now we are defining the configmap as environment variable
kind: Pod
apiVersion: v1
metadata:
  name: myenvconfig
  annotations: 
    description: "Now we are defining the configmap as environment variable !!"
  labels:
    env: development
spec:
  containers:
    - name: c00
      image: ubuntu
      args:
        - /bin/bash
        - -c
        - while true; do echo "Hello Shubham Soni" sleep 5; done
      env:
        - name: MYENV
          valueFrom:
            configMapKeyRef:
              name: mymap
              key: sample.conf
