kind: Pod
apiVersion: v1
metadata:
  name: myvolsecret
  annotations: 
    description: "ow we are working with the secret as volume mount !!"
  labels:
    env: development
spec:
  containers:
    - name: c00
      image: ubuntu
      args:
        - /bin/bash
        - -c
        - while true; do echo "Hello Shubham Soni" sleep 5; done
      volumeMounts:
        - name: testsecret
          mountPath: "/tmp/mysecrets"
  volumes:
    - name: testsecret
      secret:
        secretName: mysecret
