--- ## Now we want to expose the port via kubernetes
kind: Pod
apiVersion: v1
metadata:
  name: testpod4
  annotations:
    description: "Now we want to expose the port via kubernetes"
spec:
  containers:
    - name: c00
      image: shubhamsonirg/myimage
      env:
        - name: MYNAME
          value: SONI
  restartPolicy: Never ## Default to Always
