--- # now we are defing the limits but no requests
kind: Pod
apiVersion: v1
metadata:
  name: default-cpu-demo-2
spec:
  containers:
    - name: c00
      image: nginx
      resources:
        limits:
          cpu: "1"
