--- # Now we are working the namespace and adding the pods in it
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  annotations: 
    description: "Now we are working with the deployment in the kubernetes !!!"
  labels:
    env: development
    class: pods
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [deploy, deployment, Deployment, development]}
      - {key: myname, operator: NotIn, values: [shubham, subham, Shubham]}
  template:
    metadata:
      name: testpod
      annotations: 
        description: "this is my testpod under deployment !! under dev namespace"
      labels:
        env: development
    spec:
      containers:
        - name: c00
          image: httpd
          env:
            - name: MYNAME
              value: SHUBHAM-NAMESPACE
          ports:
            - containerPort: 80
          resources:
            requests:
                cpu: "200m"
