--- # now we are defining the requests but not limits
kind: Pod
apiVersion: v1
metadata:
  name: default-cpu-request-3
spec:
  containers:
    - name: c00
      image: nginx
      resources:
        requests:
          cpu: "0.75"
