kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
    - name: c00
      image: ubuntu
      args:
        - /bin/bash
        - -c
        - while true; do echo "Hello shubham" sleep 5; done
      env:
        - name: MYNAME
          value: RESOURCES
      resources:
        requests:
          memory: "64Mi"
          cpu:  "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
