--- ## Now we are working with the labels and selectors with the kubernetes
kind: Pod
apiVersion: v1
metadata: 
  name: testpod
  annotations:
    description: "Now we are working with the labels and selectors with the kubernetes !!!"
  labels:
    env: development
    class: pods
spec:
  containers:
    - name: c00
      image: httpd
      ports:
        - containerPort: 80

    - name: c01
      image: ubuntu
      command:  ["/bin/bash", "-c", "while true; do echo Hello-Shubham; sleep 5 ; done"]
      env:
        - name: MYNAME
          value: SHUBHAM
  restartPolicy: Never ## default is always
