--- ## Now we are working with the Node selector
kind: Pod
apiVersion: v1
metadata: 
  name: testpod6
  annotations:
    description: "Now we are working with the Node selector !!"
  labels:
    env: development
    class: pods
    love: devops
spec:
  containers: 
    - name: c00
      image: httpd
      env:
        - name: MYNAME
          value: SHUBHAM
      ports:
        - containerPort: 80
  # We have added the node selector here
  nodeSelector:
    hardware: t2.micro
  #restartPolicy: Never ## default is always
