--- ## Now we are working with the ReplicationController for scaling and replication
kind: ReplicationController
apiVersion: v1
metadata: 
  name: myreplica
  annotations: 
    description: "Now we are working with the ReplicationController for scaling and replication"
  labels:
    env: development
    class: pods
    myname: shubham
spec:
  replicas: 2
  selector:
    myname: shubham
  template:
    metadata:
      name: testpod
      annotations:
        description: "this is pod annotation for replicationController !!"
      labels:
        myname: shubham
    spec:
      containers:
        - name: c00
          image: httpd
          env:
            - name: MYNAME
              value: SHUBHAM-APACHE
          ports:
            - containerPort: 80
      nodeSelector:
        hardware: t2.micro

