--- ## Now we are creating the pods with the ReplicaSet object !!!
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myreplicaset
  annotations: 
    description: "Now we are creating the pods with the ReplicaSet object !!!"
  labels:
    env: development
    class: pods
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [development, dev, devlop]}
      - {key: myname, operator: NotIn, values: [shubham, subham, Shubham]}
  template:
    metadata:
      name: testpod
      annotations: 
        description: "this is a testpod of my docker file !!!"
      labels:
        env: development
    spec:
      containers:
        - name: c00
          image: shubhamsonirg/myimage
          env: 
            - name: SERVER
              value: APACHE-SERVER
          ports:
            - containerPort: 80
      nodeSelector:
        hardware: t2.micro
