--- ## Now instead of accessing our website through pods ip we are going to use the 
## cluster ip object in service object !!
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 80                               # cluster port exposed
      targetPort: 80                     # Pods port
  selector:
    object: deploy                      # Apply this service to any pods which has the specific label
  type: ClusterIP                       # Specifies the service type i.e ClusterIP or NodePort
