--- ## Now we are studying about the kubernetes networking communitcating with other pods in the same node !!
kind: Pod
apiVersion: v1
metadata:
  name: testpod2
  annotations:
    description: "Now we are studying about the kubernetes networking"
  labels:
    env: development
    class: pods
spec:
  containers:
    - name: c01
      image: shubhamsonirg/myimage
      ports:
        - containerPort: 80
  
  nodeSelector:
    hardware: t2.micro
